#!/bin/bash


pass = "Hol" "hol" "Holberton" "ALX" "alx" "africa" "Africa" "alxafrica" "ALXAFRICA" "AlxAfrica" "school" "HOL" "HOLBERTON"


for i in "{pass[@]}"; do
{
echo "$i" > ./101-password
./crackme3 101-password
echo "$i";
}
done
